### ISSUE TITLE
Repeatable UUIDs for debugging

### ISSUE THREAD

**Issue by alanhkarp** [uuid-rs/uuid#152]
It’s really hard to debug a program using UUIDs when they change on each run. I would really like a debug option, perhaps one that takes a value as an argument, that returns the same sequence of UUIDs on every run that supplies that value. I’ve used random number routines with that option, and it really helps when debugging.

Of course, the danger is forgetting to turn off the feature for production (something I’ve done), so you should probably provide some notification that it’s in use. A prefix on the generated UUIDs, something like DEBUG-xxxxxx, should do the trick.

**Comment by KodrAus** [comment]
It is great to be able to use the same id values in things like integration tests. The way that I've worked around this previously has been to abstract uuid generation either using a trait with multiple implementations + generics, or using a structure that has a different implementation depending on cfgs.

I think I'd rather we didn't solve this in `uuid` directly, since different use cases will want different strategies for repeatable ids.

**Comment by alanhkarp** [comment]
That's what I did, but I must not be as good a programmer as you.  It took me several hours to get something I was happy with.  If the library provided an optional parameter to the new() method, I would have saved time and gotten something I'd have more confidence in.  

As with any library, you don't want to cover every possible use case, but providing for the common ones may make sense.  Whether or not my request represents a common case is something I'll leave for the developers to decide.

**Comment by KodrAus** [comment]
> That's what I did, but I must not be as good a programmer as you.

I really doubt that :) Sorry if my response was a bit curt, I was on mobile this morning. So my thinking is that because this is a problem that might need to be solved in different ways depending on the application, and is also one that can be solved outside of the `uuid` crate, I think it's better that we don't cement a particular use case here. Mostly in the interests of having less code to maintain in the future when edge cases with our common solution pop up.

I do agree it's something folks definitely would want to do in some cases though. What if we had some examples in the `uuid` crate showing how you could create a wrapper that can give you deterministic or random ids?

**Comment by alanhkarp** [comment]
An example would do it, as long as it's easy to find.  I don't think just adding an example in the source tree would be enough.  (I doubt I would have thought to look for it.)  Perhaps a line in the description to the effect of, "If you'd like repeatable UUIDs, see (pointer to example)."

**Comment by kinggoesgaming** [comment]
I think this gave me a good idea to provide this as a separate crate. \o/. This kind of things should not be specific to UUIDs. 

As of writing, I am currently not able to test the concept as I lost my laptop's charger :cry: But as soon as I get that sorted out, I will try to test this concept out :)

If it is a successful experiment, __maybe__ we will try to get a dependency on a crate that handles that.
