### ISSUE TITLE
Break the lines in travis.yml into script files

### ISSUE THREAD

**Issue by kinggoesgaming** [uuid-rs/uuid#359]
This will help us in making a maintainable set. 

I am also thinking that this will help in creating local CI-like automation for local environments

**Comment by KodrAus** [comment]
In `env_logger`, we use [a little Rust app](https://github.com/sebasmagri/env_logger/tree/master/ci) for managing the combinations of features, since it's got a few that interact in different ways depending on what's available. If we want fuller coverage of `uuid`'s feature combinations maybe we could look at something similar here?

**Comment by kinggoesgaming** [comment]
I think I will close this issue. We are going the Github Actions route and travis may vanish altogether
