### ISSUE TITLE
How to generate uuid?

### ISSUE THREAD

**Issue by GildedHonour** [uuid-rs/uuid#474]
Documentation:

> To create a new random (V4) UUID and print it out in hexadecimal form:

> 
> // Note that this requires the `v4` feature enabled in the uuid crate.
> 
> use uuid::Uuid;
> 
> fn main() -> Result<(), Box<std::error::Error> {
>     let my_uuid = Uuid::new_v4()?;
>     println!("{}", my_uuid);
> }

Does it have to be enabled? What if I didn't enable it, how would I generate a new uuid? Is it only for v4 or for any type of uuid?

Where is that in the documenation - no where.

**Comment by Dylan-DPC** [comment]
> Does it have to be enabled? 
Yes, the feature exists so that you get only what you ask for - since most users don't need to generate each version. 

> What if I didn't enable it, how would I generate a new uuid?
You need to enable one of the features based on which version you want else it will complain that the function is not found. 

[Answer to Where is that in the documenation](https://github.com/uuid-rs/uuid#dependencies)
