### ISSUE TITLE
bug in tick calculation for v1

### ISSUE THREAD

**Issue by KarthikNedunchezhiyan** [uuid-rs/uuid#497]
**Describe the bug**

I suspect the below code has an issue. Maintainers kindly confirm whether this calculation is correct. will raise a PR if this is actually wrong.

`let ticks = UUID_TICKS_BETWEEN_EPOCHS
            + seconds * 10_000_000
            + u64::from(subsec_nanos) / 100;`

src: ﻿﻿https://github.com/uuid-rs/uuid/blob/6fde06c40ce26c11a9c41300542f431a972b2aea/src/v1.rs#L72

**Expected behavior**
I suspect the correct calculation is like below.

`let ticks = UUID_TICKS_BETWEEN_EPOCHS
            + (((seconds * 10_000_000)
            + u64::from(subsec_nanos)) / 100);`

As `UUID_TICKS_BETWEEN_EPOCHS` is already calculated for 100ns increment tick.

**Specifications (please complete the following information):**
- Version 0.8.1
- Features Enabled [v1]

**Comment by kinggoesgaming** [comment]
@uuid-rs/uuid input?

**Comment by KarthikNedunchezhiyan** [comment]
@kinggoesgaming yes, I expect the input from @uuid-rs/uuid team. based on my understanding after reading rfc4122(https://www.ietf.org/rfc/rfc4122.txt) I suspect the above calculation is wrong but I am not confident because I am a newbie.

**Comment by KarthikNedunchezhiyan** [comment]
closing this as there is no response from the maintainers.

**Comment by KodrAus** [comment]
Hey @KarthikNedunchezhiyan 

Sorry for the lack of response here. I'll re-open this one so we can investigate it properly.

**Comment by KodrAus** [comment]
Hey @KarthikNedunchezhiyan :wave: It looks like the current implementation is actually correct, but it's not easy to tell on inspection why that is.

You're right that `UUID_TICKS_BETWEEN_EPOCHS` is in 100ns increments instead of 1ns. So what we do is multiply the `seconds` value by `10_000_000` instead of `1_000_000_000` to convert it into 100ns increments, and then divide our 1ns subsec component by 100 to make it 100ns too.

Thanks for having taken the time to look at this! There's actually a lot of tricky code in this library that needs a skeptical eye.
