### ISSUE TITLE
impl Arbitrary for Uuid to enable easy integration of cargo-fuzz

### ISSUE THREAD

**Issue by blasrodri** [uuid-rs/uuid#514]
**Is your feature request related to a problem? Please describe.**
It's common to have _obejcts_ that use `Uuid`. And whenever someone wants to use `rust-fuzz`, all the components
of the _object_ need to implement/derive the [Arbitrary trait](https://docs.rs/arbitrary/1.0.0/arbitrary/trait.Arbitrary.html)

**Describe the solution you'd like**
Having an implementation for `Arbitrary` for `Uuid`

Something like this would be a starting point:

```rust
impl Arbitrary<'_> for Uuid {
    fn arbitrary(u: &mut Unstructured<'_>) -> ArbitraryResult<Self> {
        let b = u.bytes(16)?;
        Ok(Uuid::from_bytes(b.try_into().unwrap()))
    }
}
```

However, I assume it will panic most of the time. So, I'm not sure what's the best way to go about it.

**Comment by KodrAus** [comment]
I can imagine the most useful use of fuzzing with `uuid`s would be to also mess with the versions so you don't just always receive an already random `v4` uuid. If we just want to unblock `#[derive(Arbitrary)]` on types that contain `Uuid` fields though, then we could reasonably just use `uuid::Builder` to accept 16 random bytes and then set the version to `v4` so it becomes infallible.

I'd be ok with adding an optional `arbitrary` feature to `uuid`, since the crate is `1.0` and am on-board with making life easier for everyone getting started with fuzzing.

**Comment by greyblake** [comment]
Uh, I miss something like this. Alternatively an implementation could go to `Arbitrary` crate.

**Comment by KodrAus** [comment]
@greyblake At this stage `uuid` is probably the better place for it. We're working on stabilizing the library now, but until then I wouldn't expect `arbitrary` to want to add a public implementation for an unstable library 🙂
