### ISSUE TITLE
Creating UUIDv4 is very slow

### ISSUE THREAD

**Issue by mikonieminen** [uuid-rs/uuid#529]
**Describe the bug**
When creating UUIDv4 it's about 100x slower to use the default mechanism compared to for example using `rand` to generate the random bytes.

**To Reproduce**
- I've created a bench in https://github.com/mikonieminen/uuid/tree/feature/bench-creating-uuidv4
- run the bench showing the perf difference `cargo +nightly bench --features "v4" --bench v4`

**Screenshots**
```
$ cargo +nightly bench --features "v4" --bench v4
   Compiling uuid v0.8.1
    Finished bench [optimized] target(s) in 0.67s
     Running unittests (target/release/deps/v4-250371aa712188f2)

running 2 tests
test v4::create                      ... bench:       1,859 ns/iter (+/- 173)
test v4::create_using_rand_threadrng ... bench:          16 ns/iter (+/- 0)

test result: ok. 0 passed; 0 failed; 0 ignored; 2 measured; 0 filtered out; finished in 0.53s
```

**Specifications (please complete the following information):**
- Features Enabled: ["v4"]

**Other**
- feature branch having benchmark code for the issue: https://github.com/mikonieminen/uuid/tree/feature/bench-creating-uuidv4

**Comment by mikonieminen** [comment]
I'm not expert when it comes to random number generation, but as far as I've been reading using `rand` seems at least good enough for UUIDv4 needs. Is there anything I'm missing as the default implementation seems to be unacceptably slow.

**Comment by KodrAus** [comment]
Hi @mikonieminen :wave:

Are you able to share any more details of your environment? I also see `new_v4` is clearly slower than `threadrng`, but the difference is much smaller for me:

```rust
test v4::create                      ... bench:          74 ns/iter (+/- 1)
test v4::create_using_rand_threadrng ... bench:          14 ns/iter (+/- 0)
```

That's on my x86 i9 9900K Windows 10 machine with the following release profile:

```toml
[profile.release]
debug = true
opt-level = 3
lto = "fat"
codegen-units = 1
```

I did a little digging around and it looks like we are using the same underlying OS APIs between `new_v4` and `rand` (at least on Windows):

<img width="1920" alt="Left: UUID new_v4. Right: Using Rand's threadrng" src="https://user-images.githubusercontent.com/6721458/129810352-5e6b2982-e4a5-487e-a7f7-8ebad8dfb7e5.PNG">

> Left: UUID new_v4. Right: Using Rand's threadrng

I _think_ what might be happening is that because `rand` has access to more tools than `getrandom` it might only be using that underlying OS API to occasionally reseed a faster Rust-native RNG? @dhardy would know for sure.

Folks wanted `getrandom` specifically to reduce the number of dependencies when building the `v4` feature, which is widely used. If the disparity is as high as your numbers suggest for some platforms then I'd be happy to consider an optional `fast-rng` feature that switched from `getrandom` to `rand`, with the caveat that it requires more dependencies to build, not that it's less suitable for UUID generation.

**Comment by mikonieminen** [comment]
Interesting that it can have so significant difference. I'm running this on Archlinux with 5.13.10-arch1-1 kernel on Intel i7-8550U. I have also disabled hyperthreading on my system (just to mention, if that has any impact).

I did also some digging of my own and tested reading 16 bytes of random data using `rand`, `getrandom` and directly with `libc::getrandom`. Interestingly `libc::getrandom` failed with not being able to fill the whole buffer. `getrandom` succeeds, but being very slow. Maybe this issue with `libc::getrandom` is the actual root cause for the slowness?

```rust
// This seems to fail with error: "failing to fill whole buffer"
fn libc_getrandom(c: &mut Criterion) {
    c.bench_function("16 bytes random data using libc::getrandom", |b| {
        b.iter(|| {
            let bytes = 0_i128;
            let len = unsafe { libc::getrandom(bytes as *mut _, 16, libc::GRND_NONBLOCK) };
            assert_eq!(16, len);
            assert_ne!(0, bytes);
        })
    });
}
```
I just wonder if that code is correct.

**Comment by dhardy** [comment]
@KodrAus yes, `rand::thread_rng` uses only enough bytes from the OS source to seed its RNG (256 bits for ChaCha12, if I remember correctly). It also periodically reseeds, though not enough to have much performance impact. And yes, it *should* be secure enough for your needs, though the crate hasn't had a proper security audit to my knowledge.

**Comment by mikonieminen** [comment]
Thanks for the info. So I tracked this all the way to `libc::syscall` and it seems the be the source of the slowness. I also asked my colleagues to test this on their envs and they are running Ubuntu Linux on Intel (something, more recent and beefier than mine) and something based on AMD Zen2. Both of them have the same slowness for getting the random data. Also changing between `GRND_NONBLOCK` and `GRND_RANDOM` seem to have very small difference if any.

For my use case, I'm then fine using `rand::thread_rng`.

**Comment by KodrAus** [comment]
Thanks for looking into this!

I'll look at a `fast-rng` feature that pulls in `rand` and switches our rng over to it. It seems a little odd to have an additional optional feature that you'll more than likely want to enable if you make heavy use of `v4` and we might want to make it the default one day, but I'll include a note in the README suggesting libraries stick to `v4` if they need it, and apps will want to consider `fast-rng` too.
