### ISSUE TITLE
Alterantive SHA-1 Implementation

### ISSUE THREAD

**Issue by mitsuhiko** [uuid-rs/uuid#582]
**Motivation**
The master version of this crate now pulls in the rust-crypto SHA1 implementation. There is nothing wrong with this in theory but it does mean that using the v5 feature now requires pulling a lot from rust-crypto which seems a bit silly for such a minor issue. Because the crate was recently renamed the release version of uuid does pull in `sha1_smol` now which is the new name for what `sha1` referred to originally.  See https://github.com/mitsuhiko/sha1-smol/issues/42

**Solution**
I would propose to split up the v5 feature into two (eg: `v5-rust-crypto` and `v5-small`) to pick a SHA1 implementation explicitly with `v5` picking the preferred (whichever that is for you). 

**Alternatives**
1. Do nothing and keep using the rust-crypto version
2. Only support `sha1_smol`

**Is it blocking?**
It's not blocking, but it pulls in many more dependencies now.

**Anything else?**
* Issue about the sha1 -> sha1_smol rename: https://github.com/mitsuhiko/sha1-smol/issues/42

**Comment by KodrAus** [comment]
Thanks for the heads up @mitsuhiko.

We've taken a similar approach in the past with the (possibly unfortunately named) [`v4` + `fast-rng`](https://github.com/uuid-rs/uuid/blob/main/Cargo.toml#L66) combination to maintain a minimal default footprint and backwards compatibility, but allow switching in alternative implementations when there's a real user need for it.

I haven't looked through the implementations in a while (I remember them being just totally different), but if both crates are maintained then the first choice would be the smaller one (`sha1_smol`), then something like `fast-sha1` if the rust-crypto version is faster. Like you said, since our use-case is purely internal and really, really small we don't benefit from all the extra infrastructure rust-crypto makes available to us, so the reason to offer it would be because it can produce v5 UUIDs faster.
