### ISSUE TITLE
Add Changelog

### ISSUE THREAD

**Issue by brianheylin-ds** [uuid-rs/uuid#605]
**Motivation**
I want to be able to review the important changes between versions in a quick and concise manner

**Solution**
Add a CHANGELOG.md that uses a well known [format](https://keepachangelog.com/en/1.0.0/)

Thanks :wink:

**Comment by KodrAus** [comment]
Hi @brianheylin-ds :wave:

We've been using [GitHub's releases](https://github.com/uuid-rs/uuid/releases) to track changes between releases. That should have everything you need when reviewing updates, along with ready access to the diff itself.

**Comment by ralpha** [comment]
I came here to ask the same.
Even though the changes exist in the notes of the releases on github, it would still be useful to have a `CHANGELOG.md` file inside the repo. Both because of consistency across repo's. It has since become part of the workflow to check the repo for changes before updating them. It has basically become standard in all repo's to include this file.

I see this has also been partially talked about in #369. I hope you would considering adding it, even if it just includes the releases (not the unreleased changes in the repo).
