### ISSUE TITLE
Simple Encode / Decode

### ISSUE THREAD

**Issue by cuyler** [uuid-rs/uuid#676]
Hi! I'm making a simple test using bincode and Uuid and keep head-walling on the encode/decode process and I feel like I'm missing something obvious. Any pointers would be much appreciated!

```
use uuid::Uuid;
use bincode::{Encode, Decode};

#[derive(Encode, Decode, PartialEq, Debug)]
struct MyStruct {
    pub id: Uuid,
}
```

It seems like this should 'work' however, the compiler says: "the trait bound `Uuid: Encode` is not satisfied
the following other types implement trait `Encode`:"

I have included the 'serde' feature as part of the dependency:

`uuid = { version = "1.3", features = [ "v4", "fast-rng", "macro-diagnostics", "serde"] }`

This is probably something _really_ obvious and I'm just not seeing it. Seems like this should be pretty straight forward and basic, but... Thoughts?

Thank you!

**Comment by KodrAus** [comment]
Hi @cuyler 👋 

bincode is traditionally a binary format for the `serde` serialization framework but it looks like they’ve started defining their own traits for encoding/decoding too. These aren’t the same as `serde`’s, so if instead of deriving `Encode` and `Decode` you derive `Serialize` and `Deserialize` as per https://serde.rs that might help set you on the right track!

**Comment by cuyler** [comment]
Thank you! I'll give that a whirl. Appreciate the response.
