### ISSUE TITLE
UUID no longer supports serde derive attributes

### ISSUE THREAD

**Issue by daveman1010221** [uuid-rs/uuid#709]
Hello. I was updating some old code to use newer dependencies and realized that we had an old version of UUID. Attempted to update and broke the build. Tracked it down to this:  "remove the serde_derive dev dependency #408 ".  Is there a newer way to pull in serde with derive for UUID? If not, is there some reason serde derive has been banished? Thanks.

**Comment by kinggoesgaming** [comment]
Is it possible to post the exact error you are getting? AFAIK not using `serde_derive` should not affect users.

Also try depending on `serde` with `derive` feature enabled to see if it works. Again a log would be helpful.

**Comment by KodrAus** [comment]
It sounds like the problem here might have been implicitly relying on `uuid` pulling in `serde` with its `derive` feature. That's an unfortunate consequence of how Cargo builds its dependency graph and not really a problem with `uuid`. You should be able to fix your build by adding `serde_derive` to your project directly.
