### ISSUE TITLE
TryFrom<Vec<u8>> makes an unnecessary copy

### ISSUE THREAD

**Issue by pjenvey** [uuid-rs/uuid#733]
As `Vec<u8>` can be safely converted to `Bytes` instead of copying its contents.

**Comment by KodrAus** [comment]
Closing based on https://github.com/uuid-rs/uuid/pull/734#issuecomment-2008598358

If we can measure the impact of the current implementation against the new one then I'd be happy to revisit this.

**Comment by Dietr1ch** [comment]
I'm not that worried about the performance on the happy path, but a bit more concerned with untrusted inputs that arise when sending a UUID over the network or by reading files.


I'm currently parsing a UUIDv4 from bytes coming from a gRPC call, and those underlying bytes are an unbounded `Vec<u8>` which should be checked, sliced and then sort of safely [^0] made into a `Uuid`.

It'd nice to use `Uuid::try_from(msg.bytes())?`, but because I can't trust the bytes, I need to manually slice and then convert.



[^0]: A UUIDv4 has 6 fixed bits. Shouldn't we check that they match? I think there's similar restrictions on other UUID versions as there's none that's pure 128 random bits, UUIDv4 is the closest. Maybe these extra checks belong in something like `uuid::V4::TryFrom`?
